* 007 – Casino Royale (Daniel Craig) 
:PROPERTIES:
:RATING: 1
:WIKIPEDIA_LINK: https://de.wikipedia.org/wiki/James_Bond_007:_Casino_Royale
:YEAR: 2006
:LENGTH: 144
:ORIGINAL_TITLE: Casino Royale
:ORIGINAL_LANGUAGE: en
:DIRECTOR: Martin Campbell
:END:

Casino Royale zeigt James Bonds Weg zum vollwertigen 00-Agenten. Nach einem ersten Auftrag gegen einen Verräter erhält Bond seine Lizenz und stößt auf den Terrorfinanzier Le Chiffre, der Geld eines afrikanischen Warlords verspielt hat. Bonds Ermittlungen führen von Madagaskar über die Bahamas nach Miami, wo er ein Attentat verhindert und Le Chiffre finanziell ruiniert. Um das verlorene Geld zurückzugewinnen, setzt Le Chiffre alles auf ein hochdotiertes Pokerturnier in Montenegro. Bond tritt dort mit Unterstützung des MI6, des CIA und der Schatzamtsbeamtin Vesper Lynd an, zu der er eine Beziehung entwickelt. Trotz Rückschlägen, Verrat, Vergiftung und Folter gewinnt Bond das Turnier. Le Chiffre wird daraufhin von Mr. White getötet. Bond und Vesper planen ein gemeinsames Leben, doch in Venedig entpuppt sich Vesper als erpresste Verräterin und stirbt. Bond verfolgt die Spur bis zu Mr. White und präsentiert sich endgültig als James Bond.

* 007 - Quantum Trost (Ein_Daniel Craig)
:PROPERTIES:
:RATING: +
:END:

* 100.000 Dollar in der Sonne (F/IT ´1964_/Trailer)
:PROPERTIES:
:RATING: + (?)
:END:

* 1000 Arten, Regen zu beschreiben (D ´2017)
:PROPERTIES:
:RATING: +
:END:

* 1000 Mexikaner (D '2016_/Trailer)
:PROPERTIES:
:RATING: -
:END:

* 1001 Gramm (N/D ´2014_/Trailer)
:PROPERTIES:
:RATING:
:END:
